### ISSUE TITLE
Unreadable comments 

### ISSUE THREAD

**Issue by expiredy101** [expiredy101/EmotionDetectionAi#21]
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L3
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L23-L26
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L29
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L49-L50
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L53
https://github.com/expiredy101/EmotionDetectionAi/blob/5be8c320194db7bf9866262a6ba5755303fcdb80/presentation/MarketSimulator/Assets/scripts/Playercontroller.cs#L66-L67

In this character-controller script we got a kinda strange comment lines, hope somebody will fix them soon

**Comment by expiredy** [comment]
So, cause i rewrite entire script from zero...) There is no more unreadable comments
